#!/usr/bin/env bash

GREEN="\033[1;32mm"
YELLOW="\033[1;33m"
DEFAULT="\033[0m"

main() {
	require-tunnelblick

	local operation="$1"

	$operation
}

list() {
	local names=($(tunnelblick-do "get name of configurations" | tr -d ','))
	for name in "${names[@]}"
	do
		case $(state $name) in
			"EXITING")
				char=" "
				;;
			"CONNECTED")
				char="*"
				;;
			*)
				char="~"
				;;
		esac
		printf "%s %s\n" "$char" "$name"
	done
}

state() {
	local name="$1"

	tunnelblick-do "get state of first configuration where name = \"$name\""
}

tunnelblick-do() {
	local command="$1"

	osascript -e "tell application \"Tunnelblick\"" -e "$command" -e "end tell"
}

require-tunnelblick() {
	if [[ -z $(mdfind "kMDItemKind == \"Application\"" | grep "Tunnelblik.app") ]]; then
		echo
		echo "Whoops! Tunnelblick doesn't seem to be installed on your machine."
    echo "You can install Tunnelblick by using homebrew (cask):"
    echo
    echo -e "	${YELLOW}brew cask install tunnelblick${DEFAULT}"

		exit 1
	fi
}

main "$@"