#!/usr/bin/env bash

GREEN="\033[1;32mm"
YELLOW="\033[1;33m"
DEFAULT="\033[0m"

CONNECTED="CONNECTED"
DISCONNECTED="EXITING"

main() {
	require-tunnelblick

	"$1"
}

list() {
	local vpn_names=($(tunnelblick-do "get name of configurations" | tr -d ','))
	local vpn_states=($(tunnelblick-do "get state of configurations" | tr -d ','))

	for i in "${!vpn_names[@]}"
	do
		vpn_name=${vpn_names[$i]}
		case "${vpn_states[$i]}" in
			"$CONNECTED") 	 echo "* $vpn_name" ;;
			"$DISCONNECTED") echo "  $vpn_name" ;;
			*) 							 echo "~ $vpn_name" ;;
		esac
	done
}

state() {
	local vpn_name="$1"

	tunnelblick-do "get state of all"
}

tunnelblick-do() {
	local command="$1"

	osascript -e "tell application \"Tunnelblick\"" -e "$command" -e "end tell"
}

require-tunnelblick() {
	if [[ -z $(mdfind "kMDItemKind == \"Application\"" | grep "Tunnelblick.app") ]]; then
		echo
		echo "Whoops! Tunnelblick doesn't seem to be installed on your machine."
    echo "You can install Tunnelblick by using homebrew (cask):"
    echo
    echo -e "	${YELLOW}brew cask install tunnelblick${DEFAULT}"

		exit 1
	fi
}

main "$@"